<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="IsInfinity" Id="{d2100733-1537-4ab5-ad1d-c169a14f6240}" SpecialFunc="None">
    <Declaration><![CDATA[// Struckig
// Copyright (C) 2022 Stefan Besler

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with THIS PROGRAM.  IF NOT, see <http://www.gnu.org/licenses/>.
FUNCTION IsInfinity : BOOL
VAR_INPUT
  value : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsInfinity := value = Constants.Infinity OR_ELSE value = -Constants.Infinity;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>