<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LrealBits" Id="{2ba3985e-b034-4f38-8371-b63f2efef357}" SpecialFunc="None">
    <Declaration><![CDATA[// Struckig
// Copyright (C) 2022 Stefan Besler

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with THIS PROGRAM.  IF NOT, see <http://www.gnu.org/licenses/>.
{attribute 'hide'}
FUNCTION LrealBits : ULINT
VAR_INPUT
  x : LREAL;
END_VAR
VAR
  b : POINTER TO ULINT := ADR(x);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[LrealBits := b^;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>