<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LrealFromBits" Id="{26af1350-f1f7-4775-a258-be47fc01563f}" SpecialFunc="None">
    <Declaration><![CDATA[// Struckig
// Copyright (C) 2022 Stefan Besler

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with THIS PROGRAM.  IF NOT, see <http://www.gnu.org/licenses/>.
{attribute 'hide'}
FUNCTION LrealFromBits : LREAL
VAR_INPUT
  b : ULINT;
END_VAR
VAR
  x : POINTER TO LREAL := ADR(b);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[LrealFromBits := x^;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>