<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Power2" Id="{0e3e86d0-3b11-44f2-b301-06ab88dcd5f9}" SpecialFunc="None">
    <Declaration><![CDATA[// Struckig
// Copyright (C) 2022 Stefan Besler

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with THIS PROGRAM.  IF NOT, see <http://www.gnu.org/licenses/>.
FUNCTION INTERNAL Power2 : LREAL
VAR_INPUT
  v : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Power2 := v*v;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>