<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LrealBits" Id="{2ba3985e-b034-4f38-8371-b63f2efef357}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'hide'}
FUNCTION LrealBits : ULINT
VAR_INPUT
  x : LREAL;
END_VAR
VAR
  b : POINTER TO ULINT := ADR(x);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[LrealBits := b^;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>