<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{f725f308-f3c1-4da3-8197-2078a75fc02b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
  mathTest : MathTest;
  minDurationTest : MinDurationTest;
  velocityInterfaceTest : VelocityInterfaceTest;
  knownExamplesTest : KnownExamplesTest;
  secondaryFeaturesTest : SecondaryFeaturesTest;
  debuggedExamplesTest : DebuggedExamplesTest;
  targetPosTest : TargetPosTest;
  targetPosAccTest : TargetPosAccTest;
  targetPosVelTest : TargetPosVelTest;
  targetPosVelAccTest : TargetPosVelAccTest;
  propagateTest : PropagateTest;
  // generatedTest : GeneratedTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>